/**
 * WVault Input Validation Utilities
 * Comprehensive validation and sanitization functions
 */

const { LIMITS, ALLOWED_PROTOCOLS, UUID_REGEX, SQL_KEYWORDS, COMMON_PATTERNS } = require('./constants');

/**
 * Sanitize a file ID to prevent path traversal
 * Only allows UUID format
 * @param {string} fileId - File ID to validate
 * @returns {string|null} Sanitized ID or null if invalid
 */
function sanitizeFileId(fileId) {
    if (typeof fileId !== 'string') return null;
    // Accept standard UUID format (xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx)
    if (UUID_REGEX.test(fileId)) return fileId.toLowerCase();
    // Also accept 32-char lowercase hex strings (generated by crypto.randomBytes(16).toString('hex'))
    if (/^[0-9a-f]{32}$/i.test(fileId)) return fileId.toLowerCase();
    return null;
}

/**
 * Validate credential ID
 * @param {*} id - ID to validate
 * @returns {number|null} Validated ID or null
 */
function validateCredentialId(id) {
    const num = parseInt(id, 10);
    if (isNaN(num) || num < 1 || num > LIMITS.MAX_ID_VALUE) return null;
    return num;
}

/**
 * Validate folder ID
 * @param {*} id - Folder ID to validate
 * @returns {number|null} Validated ID or null
 */
function validateFolderId(id) {
    if (id === null || id === undefined) return null;
    const num = parseInt(id, 10);
    if (isNaN(num) || num < 1 || num > LIMITS.MAX_ID_VALUE) return null;
    return num;
}

/**
 * Validate and sanitize SQL identifiers
 * @param {string} identifier - SQL identifier
 * @returns {string|null} Sanitized identifier or null
 */
function sanitizeSqlIdentifier(identifier) {
    if (typeof identifier !== 'string') return null;
    // Only allow alphanumeric and underscores, must start with letter or underscore
    if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(identifier)) return null;
    // Check against SQL keywords
    if (SQL_KEYWORDS.includes(identifier.toUpperCase())) return null;
    return identifier;
}

/**
 * Validate URL to prevent SSRF
 * @param {string} url - URL to validate
 * @returns {string|null} Validated URL or null
 */
function validateUrl(url) {
    if (typeof url !== 'string' || url.length > 2048) return null;
    try {
        const parsed = new URL(url);
        if (!ALLOWED_PROTOCOLS.includes(parsed.protocol)) return null;
        return url;
    } catch {
        return null;
    }
}

/**
 * Validate domain for icon lookup
 * @param {string} domain - Domain string
 * @returns {string} Sanitized domain
 */
function sanitizeDomain(domain) {
    if (!domain || typeof domain !== 'string') return '';

    return domain
        .toLowerCase()
        .replace(/^https?:\/\//, '')
        .split('/')[0]
        .replace(/\s+/g, '')
        .replace(/[^a-z0-9.-]/g, '');
}

/**
 * Validate password strength
 * @param {string} password - Password to validate
 * @returns {Object} Validation result
 */
function validatePasswordStrength(password) {
    if (typeof password !== 'string') {
        return { valid: false, error: 'Password must be a string' };
    }

    if (password.length < 8) {
        return { valid: false, error: 'Password must be at least 8 characters' };
    }

    if (password.length > 1000) {
        return { valid: false, error: 'Password must not exceed 1000 characters' };
    }

    // Check for common weak patterns
    const lowerPass = password.toLowerCase();
    for (const pattern of COMMON_PATTERNS) {
        if (lowerPass.includes(pattern)) {
            return { valid: false, error: 'Password contains common weak patterns' };
        }
    }

    return { valid: true };
}

/**
 * Validate file path to prevent traversal
 * @param {string} filePath - File path to validate
 * @param {string} basePath - Allowed base directory
 * @returns {boolean} True if path is safe
 */
function isSafeFilePath(filePath, basePath) {
    if (!filePath || typeof filePath !== 'string') return false;

    const path = require('path');
    const resolvedPath = path.resolve(filePath);
    const resolvedBase = path.resolve(basePath);

    return resolvedPath.startsWith(resolvedBase);
}

/**
 * Validate file size
 * @param {number} size - File size in bytes
 * @param {number} maxSize - Maximum allowed size
 * @returns {boolean} True if size is acceptable
 */
function validateFileSize(size, maxSize = LIMITS.MAX_FILE_SIZE) {
    return typeof size === 'number' && size > 0 && size <= maxSize;
}

/**
 * Sanitize string for display (XSS prevention)
 * @param {string} text - Text to sanitize
 * @returns {string} Sanitized text
 */
function sanitizeDisplayText(text) {
    if (!text || typeof text !== 'string') return '';

    return text
        .replace(/&/g, '&amp;')
        .replace(/</g, '&lt;')
        .replace(/>/g, '&gt;')
        .replace(/"/g, '&quot;')
        .replace(/'/g, '&#039;');
}

/**
 * Validate TOTP secret format
 * @param {string} secret - TOTP secret
 * @returns {boolean} True if valid
 */
function validateTotpSecret(secret) {
    if (!secret || typeof secret !== 'string') return false;
    if (secret.length > 256) return false;
    // Base32 validation
    return /^[A-Z2-7]+=*$/i.test(secret);
}

/**
 * Validate search query
 * @param {string} query - Search query
 * @returns {string|null} Validated query or null
 */
function validateSearchQuery(query) {
    if (!query || typeof query !== 'string') return null;
    if (query.length > 256) return null;
    // Remove potentially dangerous characters but keep common search chars
    return query.replace(/[<>'"]/g, '');
}

/**
 * Validate email format
 * @param {string} email - Email to validate
 * @returns {boolean} True if valid
 */
function validateEmail(email) {
    if (!email || typeof email !== 'string') return false;
    // Simple email regex
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email);
}

/**
 * Safe JSON parse with fallback
 * @param {string} json - JSON string
 * @param {*} fallback - Fallback value
 * @returns {*} Parsed value or fallback
 */
function safeJsonParse(json, fallback = null) {
    if (!json || typeof json !== 'string') return fallback;
    // Prevent prototype pollution
    if (json.includes('__proto__') || json.includes('constructor')) return fallback;
    try {
        return JSON.parse(json);
    } catch (e) {
        return fallback;
    }
}

/**
 * Validate hex string
 * @param {string} hex - Hex string
 * @returns {boolean} True if valid
 */
function validateHex(hex) {
    if (!hex || typeof hex !== 'string') return false;
    return /^[0-9a-f]+$/i.test(hex);
}

/**
 * Validate PIN format
 * @param {string} pin - PIN to validate
 * @param {number} length - Required length (default 4)
 * @returns {boolean} True if valid
 */
function validatePin(pin, length = 4) {
    if (!pin || typeof pin !== 'string') return false;
    if (pin.length !== length) return false;
    return /^\d+$/.test(pin);
}

module.exports = {
    sanitizeFileId,
    validateCredentialId,
    validateFolderId,
    sanitizeSqlIdentifier,
    validateUrl,
    sanitizeDomain,
    validatePasswordStrength,
    isSafeFilePath,
    validateFileSize,
    sanitizeDisplayText,
    validateTotpSecret,
    validateSearchQuery,
    validateEmail,
    safeJsonParse,
    validateHex,
    validatePin
};
